### ISSUE TITLE
How to increase the number of results?

### ISSUE THREAD

**Issue by Pratiksha29** [commonsense/conceptnet5#104]
How to increase the number of results? which we get when we hit URL "http://api.conceptnet.io/c/en/india", as by default, it give 20 nodes.

**Comment by rspeer** [comment]
Use the `limit` parameter: http://api.conceptnet.io/c/en/india?limit=100

Issue reports aren't the best place for questions. I suggest the Gitter chat: https://gitter.im/commonsense/conceptnet5
