### ISSUE TITLE
[Question] Not an issue: 

### ISSUE THREAD

**Issue by mobab** [commonsense/conceptnet5#134]
Greetings,

I am accessing ConceptNet from Java,

1- i have found no documentation at all about using Conceptnet with Java, not even simple examples.

2- how to get the things which appear for example under category "is used for" or under the category "is a type of" for example for the item Chain, if i do it manually using the webpage http://conceptnet.io/c/en/chain it seems straight forwards you can see that a chain is used for decoration, hit someone (not recommended ), connect, fasten, holding a dog, etc.

The following Java code uses two Maven dependencies: 1- org.apache.commons.io.IOUtils 2- org.json

```
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.Charset;

import org.apache.commons.io.IOUtils;
import org.json.JSONArray;
import org.json.JSONObject;

public class Main {

    public static void main(String[] args) 
    {
        try 
        {
            // url containing the word to be indexed
            String obj = "http://api.conceptnet.io/c/en/example";
            // open HttpURLConnection
            HttpURLConnection hp = (HttpURLConnection) new URL(obj)
                    .openConnection();
            // set to request method to get
            // not required since default
            hp.setRequestMethod("GET");
            // get the inputstream in the json format
            hp.setRequestProperty("Accept", "application/json");
            // get inputstream from httpurlconnection
            InputStream is = hp.getInputStream();
            // get text from inputstream using IOUtils
            String jsonText = IOUtils.toString(is, Charset.forName("UTF-8"));
            // get json object from the json String
            JSONObject json = new JSONObject(jsonText);
            // get the edges array from the JSONObject which contains all
            // content
            JSONArray edges = json.getJSONArray("edges");
            // goes through the edges array
            for (int x = 0; x < edges.length(); x++) 
            {
                // convert the first object of the json array into a jsonobject
                // once it is a jsonobject you can use getString or getJSONArray
                // to continue in getting info
                System.out.println(
                        edges.getJSONObject(x));
            }
            is.close();
        }
        catch (Exception e) {
            e.printStackTrace();
        }

    }

}
```

That code loops on the edges one by one and print the content.

**So** How to access specific things inside the edge, for example things under "is used for"?

3- i have noticed that 

http://conceptnet.io/c/en/chain is different than http://api.conceptnet.io/c/en/chain

for example there is no information about isUsedFor and many other things are missing.

Thanks in advance for your time.
Sincere regards

**Comment by rspeer** [comment]
Using the API is the right way to use ConceptNet with Java.

The API results are in pages. To get more results, follow the `view["nextPage"]` link.
