### ISSUE TITLE
db/wiktionary.py file reference in lemmatize.py: does not exist (pip install)

### ISSUE THREAD

**Issue by prijatelj** [commonsense/conceptnet5#149]
I am using the pip installed version of conceptnet5 and I am attempting to make use of the Conceptnet Numberbatch word embeddings. To do so I need to lemmatize my input so that it matches that of the ConcepNet word embeddings.

```
from conceptnet5.language.lemmatize import lemmatize
lemmatize("en", "hens")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/commoner/.local/lib/python3.6/site-packages/conceptnet5/language/lemmatize.py", line 219, in lemmatize
    return LEMMATIZER.lookup(language, word, pos)
  File "/home/commoner/.local/lib/python3.6/site-packages/conceptnet5/language/lemmatize.py", line 137, in lookup
    self.db = sqlite3.connect(self.filename)
sqlite3.OperationalError: unable to open database file 
```
When I attempt to lemmatize, I receive the error above. After checking the lemmatize file here on the master branch, I noticed that it imports the database wiktionary file from "db/wiktionary.py". which does not exist there. Instead I did find a wiktionary.py to exist in the `readers` directory. Is this the actual file required?

I thought you should know in case some change in location of the file did not get noticed for lemmatize.py. If I am incorrect on something and this is intended, please let me know how I may overcome this issue. Thank you.

**Comment by rspeer** [comment]
I think you meant `db/wiktionary.db`, not `wiktionary.py`. It's a SQLite database that's produced as part of the ConceptNet build process. If you haven't built ConceptNet, you don't have it.

Anyway, the current version of ConceptNet Numberbatch doesn't require lemmatization; it contain all the word forms separately.
