### ISSUE TITLE
Unable to install Conceptnet in VM 

### ISSUE THREAD

**Issue by Roshni1988** [commonsense/conceptnet5#159]
Hello,

I am not able to load the Data to PostgreSQl Database. I get the following error.

{
  "@context": [
    "http://api.conceptnet.io/ld/conceptnet5.5/context.ld.json",
    "http://api.conceptnet.io/ld/conceptnet5.5/pagination.ld.json"
  ],
  "error": {
    "details": "The ConceptNet database has not been built.",
    "status": 503
  }
}

I get the below logs. I am not sure why the data base is not loaded with the Data Properly. Due to which data is not fetched in Web.

**Comment by rspeer** [comment]
I'm going to need more information. What method are you following, and what do the logs say?

**Comment by neatbasis** [comment]
docker-compose up --build
fails at:
db_1   | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/10-download.sh
db_1   | mkdir: cannot create directory ‘/data/conceptnet/psql’: Permission denied

**Comment by rspeer** [comment]
I think this is the same issue as #172.
