### ISSUE TITLE
When runining the ./build.sh caused filename not matched error.

### ISSUE THREAD

**Issue by terU3760** [commonsense/conceptnet5#160]
..........
..........
..........
rule extract_raw:
    input: data/raw/conceptnet-raw-data-5.6.zip
    output: data/raw/emoji/es_MX.xml
    jobid: 428
    wildcards: dirname=emoji, filename=es_MX.xml

Archive:  data/raw/conceptnet-raw-data-5.6.zip
caution: filename not matched:  raw/emoji/es_MX.xml
Error in rule extract_raw:
    jobid: 428
    output: data/raw/emoji/es_MX.xml

RuleException:
CalledProcessError in line 182 of /**********/conceptnet5/Snakefile:
Command ' set -euo pipefail;  unzip data/raw/conceptnet-raw-data-5.6.zip raw/emoji/es_MX.xml -d data ' returned non-zero exit status 11.
  File "/**********/conceptnet5/Snakefile", line 182, in __rule_extract_raw
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run

Finished job 411.
19 of 448 steps (4%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /**********/conceptnet5/.snakemake/log/2018-02-22T202445.051217.snakemake.log

Could anyone please give me a hand?

**Comment by rspeer** [comment]
We messed this up -- we started using a newer version of the emoji data, which has more files, without putting those files in the raw data package.

#161 is a patch to download the emoji data separately, which should fix this.

**Comment by jlowryduda** [comment]
@terU3760, this is now fixed. That's for letting us know!
