### ISSUE TITLE
When running ./build.sh caused: Error in rule prepare_db

### ISSUE THREAD

**Issue by terU3760** [commonsense/conceptnet5#162]
..........
..........
..........

/bin/bash: line 1:  2048 Killed                  cn5-db prepare_data data/assertions/assertions.msgpack data/psql
Error in rule prepare_db:
    jobid: 15
    output: data/psql/edges.csv, data/psql/edge_sources.csv, data/psql/edge_features.csv, data/psql/nodes.csv, data/psql/node_prefixes.csv, data/psql/sources.csv, data/psql/relations.csv

RuleException:
CalledProcessError in line 423 of /**********/conceptnet5/Snakefile:
Command ' set -euo pipefail;  cn5-db prepare_data data/assertions/assertions.msgpack data/psql ' returned non-zero exit status 137.
  File "/**********/conceptnet5/Snakefile", line 423, in __rule_prepare_db
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Removing output files of failed job prepare_db since they might be corrupted:
data/psql/edges.csv, data/psql/edge_sources.csv, data/psql/edge_features.csv, data/psql/node_prefixes.csv
Finished job 32.
402 of 426 steps (94%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /**********/conceptnet5/.snakemake/log/2018-02-23T133240.771818.snakemake.log

**Comment by rspeer** [comment]
"Killed" means that something in the operating system killed the process. Is it possible that you ran out of memory?

**Comment by terU3760** [comment]
@rspeer Yes, that was the cause. Thank you so much! This problem is solved.
