### ISSUE TITLE
Error in rule download_raw

### ISSUE THREAD

**Issue by eler** [commonsense/conceptnet5#167]
When I build conceptNet on my server，I get this error.

Error in rule download_raw:
    jobid: 28
    output: data/raw/vectors/GoogleNews-vectors-negative300.bin.gz

RuleException:
CalledProcessError in line 146 of /home/wanglong/conceptnet5/Snakefile:
Command ' set -euo pipefail;  curl -f http://conceptnet.s3.amazonaws.com/raw-data/2016/vectors/GoogleNews-vectors-negative300.bin.gz > data/raw/vectors/GoogleNews-vectorss
-negative300.bin.gz ' returned non-zero exit status 56
  File "/home/wanglong/conceptnet5/Snakefile", line 146, in __rule_download_raw
  File "/usr/local/python3.5/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job download_raw since they might be corrupted:
data/raw/vectors/GoogleNews-vectors-negative300.bin.gz
Error in rule download_raw:
    jobid: 135
    output: data/raw/vectors/glove12.840B.300d.txt.gz

**Comment by rspeer** [comment]
Curl's exit status 56 means that the download was interrupted. You should probably just try again.

On the master branch, we're switching from curl to wget, which has the ability to automatically reconnect.
