### ISSUE TITLE
What functions built in conceptnet5 can be applied to find the other objects related to given ones in a little complex situation?

### ISSUE THREAD

**Issue by terU3760** [commonsense/conceptnet5#168]
I have the following requirements to fiddle with conceptnet.

In each situation, I have some words such as: "person" "sheep" "cow" "horse". I want find other objects related to them. For instance, "grass" ... Are there any functions conceptnet provide to fulfill such like tasks? If there are, may I have the general idea of what kind of algorithms it is running. The old version of ConceptNet in the paper: "ConceptNet ---- a practical commonsense reasoning tool-kit" has some function called GetContext or something. Is there a counterpart here in conceptnet5?

It seems there is term-term matrix representation of the ConceptNet graph. Is it possible to directly manipulate it.

I'm a newbie of conceptnet. I have no idea of what documents to read and what steps to follow to complete the above task. Thanks in advance.

**Comment by rspeer** [comment]
This can be done with the relatedness API: http://api.conceptnet.io/related/list/en/person,sheep,cow,horse?filter=/c/en

If you're looking for something more complex, it's probably not the role of ConceptNet to provide a one-size-fits-all solution; instead ConceptNet provides the data for your solution. But yes, we can support simple queries for relatedness (and the results should be a lot better than what you would have gotten from ConceptNet 2's "GetContext").
