### ISSUE TITLE
A few nigglings about the similar_terms function.

### ISSUE THREAD

**Issue by terU3760** [commonsense/conceptnet5#171]
How to control the number of returned terms of the similar_terms function? By default it is 20, is it possible to increase or decrease it?
It seems in some situations the similar_terms function will cause IOError even the passed-in terms do exist in the concept database. In what case will it cause IOError or any other errors?

**Comment by rspeer** [comment]
The `similar_terms` function takes a `limit` parameter, which defaults to 20.

I can't debug your IOError unless you show me the command you ran and the complete traceback.
