### ISSUE TITLE
Starting from in between.

### ISSUE THREAD

**Issue by Vyso** [commonsense/conceptnet5#176]
This is probably a very trivial doubt, but I really don't know how to do so, and so I ask.
In the given build process (https://github.com/commonsense/conceptnet5/wiki/Build-process), in case I stopped the process at 94% and wanted to pick up again from that stop, from a particular job id, is there any way I could do that?

**Comment by rspeer** [comment]
You've still got all the files that were built so far, so simply re-running `./build.sh` or `snakemake` should resume where you were in the process.
