### ISSUE TITLE
adding VNF: Sqlite3 unable to open database file

### ISSUE THREAD

**Issue by medhmi** [commonsense/conceptnet5#180]
hi, i tried to run example of adding a new VNF on escape (https://www.youtube.com/watch?v=7pp_X2C_OvI) but when i execute the command for reseting the vnfCatalog  this error is shown:

- mininet@mininet-vm:~/escape/mininet/examples$ sudo python vnfcatalog-reset.py 
- [sudo] password for mininet: 
- Traceback (most recent call last):
-   File "vnfcatalog-reset.py", line 89, in <module>
-     'nat','testVnf'])
-   File "vnfcatalog-reset.py", line 26, in del_VNFs
-     if Catalog().get_VNF(vnf_name = vnf) != []:
-   File "build/bdist.linux-x86_64/egg/mininet/vnfcatalog.py", line 45, in __init__
-   File "build/bdist.linux-x86_64/egg/mininet/vnfcatalog.py", line 62, in load
- sqlite3.OperationalError: unable to open database file

**Comment by jlowryduda** [comment]
This doesn't seem to be related to ConceptNet. Did you mean to post it here?
