### ISSUE TITLE
Error in DB restore

### ISSUE THREAD

**Issue by Vishnubala95** [commonsense/conceptnet5#186]
Hi,
I tried to implement this in our own server and always ended up with the same error even though tried both of the methods for the setup :
    1. Docker
    2. Snake make

Kindly have a look at this and help me, solving  the issue.

**Docker result:**

o https://flask-limiter.readthedocs.org/#rate-limit-domain for the recommended configuration
conceptnet-web_1  |   " for the recommended configuration", UserWarning
conceptnet-web_1  | /usr/local/lib/python3.5/site-packages/flask_limiter/extension.py:640: UserWarning: global_limits was a badly name configuration since it is actually a def
ault limit and not a  globally shared limit. Use default_limits if you want to provide a default or use application_limits  if you intend to really have a global shared limit
conceptnet-web_1  |   " if you intend to really have a global shared limit", UserWarning
conceptnet-web_1  | WSGI app 0 (mountpoint='') ready in 1 seconds on interpreter 0x1850790 pid: 10 (default app)
conceptnet-web_1  | uWSGI running as root, you can use --uid/--gid/--chroot options
conceptnet-web_1  | *** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
conceptnet-web_1  | *** uWSGI is running in multiple interpreter mode ***
conceptnet-web_1  | spawned uWSGI master process (pid: 10)
conceptnet-web_1  | spawned uWSGI worker 1 (pid: 38, cores: 1)
conceptnet-web_1  | spawned uWSGI worker 2 (pid: 39, cores: 1)
db_1              | CREATE DATABASE
db_1              | 
db_1              | ALTER ROLE
db_1              | 
db_1              | 
db_1              | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/10-check-download.sh
db_1              | mkdir: cannot create directory ‘/data/conceptnet/psql’: Permission denied
conceptnet-web_1  | 2018-04-09 08:43:06,268 INFO success: nginx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
conceptnet-web_1  | 2018-04-09 08:43:06,268 INFO success: uwsgi2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
conceptnet-web_1  | 2018-04-09 08:43:06,268 INFO success: uwsgi1 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
conceptnet-web_1  | [pid: 38|app: 0|req: 1/1] 172.18.0.1 () {30 vars in 355 bytes} [Mon Apr  9 08:52:44 2018] GET /c/en/example => generated 3178 bytes in 28 msecs (HTTP/1.1 5
03) 2 headers in 98 bytes (1 switches on core 0)
conceptnet-web_1  | 172.18.0.1 - - [09/Apr/2018:08:52:44 +0000] "GET /c/en/example HTTP/1.1" 503 3178 "-" "curl/7.47.0"
conceptnet-web_1  | [pid: 38|app: 0|req: 2/2] 172.18.0.1 () {30 vars in 345 bytes} [Mon Apr  9 08:56:05 2018] GET /c/India => generated 3178 bytes in 1 msecs (HTTP/1.1 503) 2 
headers in 98 bytes (1 switches on core 0)
conceptnet-web_1  | 172.18.0.1 - - [09/Apr/2018:08:56:05 +0000] "GET /c/India HTTP/1.1" 503 3178 "-" "curl/7.47.0"
conceptnet-web_1  | [pid: 38|app: 0|req: 3/3] 172.18.0.1 () {30 vars in 351 bytes} [Mon Apr  9 09:14:54 2018] GET /c/en/India => generated 3178 bytes in 1 msecs (HTTP/1.1 503)
 2 headers in 98 bytes (1 switches on core 0)
conceptnet-web_1  | 172.18.0.1 - - [09/Apr/2018:09:14:54 +0000] "GET /c/en/India HTTP/1.1" 503 3178 "-" "curl/7.47.0"
conceptnet-web_1  | [pid: 38|app: 0|req: 4/4] 172.18.0.1 () {30 vars in 351 bytes} [Mon Apr  9 09:15:08 2018] GET /c/en/India => generated 3178 bytes in 1 msecs (HTTP/1.1 503)
 2 headers in 98 bytes (1 switches on core 0)
conceptnet-web_1  | 172.18.0.1 - - [09/Apr/2018:09:15:08 +0000] "GET /c/en/India HTTP/1.1" 503 3178 "-" "curl/7.47.0"
conceptnet-web_1  | [pid: 39|app: 0|req: 1/5] 172.18.0.1 () {30 vars in 361 bytes} [Mon Apr  9 10:15:37 2018] GET /c/en/university => generated 3178 bytes in 30 msecs (HTTP/1.
1 503) 2 headers in 98 bytes (1 switches on core 0)
conceptnet-web_1  | 172.18.0.1 - - [09/Apr/2018:10:15:37 +0000] "GET /c/en/university HTTP/1.1" 503 3178 "-" "curl/7.47.0"
conceptnet5550_conceptnet-web_1 exited with code 137

**SnakeMake :**
Database Not Updated
Exited

**Comment by rspeer** [comment]
This is apparently the same as #172, so I'll direct further discussion there.
