### ISSUE TITLE
 conceptnet-assertions-5.5.5.csv and http://conceptnet.io  are not Coincident.

### ISSUE THREAD

**Issue by phiedulxp** [commonsense/conceptnet5#187]
I load assertions to neo4j, but find that concept such as /c/en/u.s.a. is lack of /r/IsA relation but it exist in conceptnet.io browser, and some concept have self-direct relation. I will also check my code, but I'm not sure where the error come from?

**Comment by phiedulxp** [comment]
I get result from neo4j import:
Import completed successfully, took 1m 15s 167ms. Imported:
  3433120 nodes
  1716878 relationships
  8583118 properties

**Comment by RJ2494** [comment]
I have downloaded and stored the precomputed Postgresql data of ConceptNet on my local machine. I am also getting the different result sets. For example -  when I try to find the terms 'Related To' the term 'usa'
(1) On my local machine -
I get 136 terms
(2) On conceptnet.io - 
I get more than 1000 terms.

Please explain

**Comment by RJ2494** [comment]
But the schemes of  assertions.csv file and  'edges' table in Postgresql are not same i.e. it's not in the form which I can directly download into my database tables.
Are there prebuilt data of postgresql tables for ConceptNet 5.6 available?

**Comment by rspeer** [comment]
We don't currently have a separate download for those. They're present in the [AWS image](https://github.com/commonsense/conceptnet5/wiki/Running-your-own-copy) and of course you get them by running the [build process](https://github.com/commonsense/conceptnet5/wiki/Build-process).
