### ISSUE TITLE
AWS image can't find templates for Web frontend; possibly running old version of code

### ISSUE THREAD

**Issue by rolisz** [commonsense/conceptnet5#188]
I followed the steps from the project wiki for Running your own copy in AWS. The image starts up well and up to "curl http://localhost/c/en/example" it works fine. This returns an expected JSON with all the edges. 

But, when I do "curl http://www.conceptnet.localhost" or if I try to access the instance through the external address, I get a 502 Bad Gateway error.

The output of  "journalctl -u conceptnet" is:
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]: Traceback (most recent call last):
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/app.py", line 1639, in full_
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     rv = self.dispatch_request()
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/app.py", line 1625, in dispa
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return self.view_functions[rule.endpoint](**req.view_args)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/conceptnet5/web/conceptnet_web/web.py", line 61, in front_page
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return flask.render_template('index.html', languages=languages)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/templating.py", line 133, in
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/jinja2/environment.py", line 869,
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return self.get_template(template_name_or_list, parent, globals)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/jinja2/environment.py", line 830,
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return self._load_template(name, self.make_globals(globals))
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/jinja2/environment.py", line 804,
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     template = self.loader.load(self, name, globals)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in l
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     source, filename, uptodate = self.get_source(environment, name)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/templating.py", line 57, in
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return self._get_source_fast(environment, template)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/templating.py", line 85, in
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     raise TemplateNotFound(template)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]: jinja2.exceptions.TemplateNotFound: index.html
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]: During handling of the above exception, another exception occurred:
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]: Traceback (most recent call last):
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/app.py", line 1988, in wsgi_
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     response = self.full_dispatch_request()
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/app.py", line 1641, in full_
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     rv = self.handle_user_exception(e)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/app.py", line 1545, in handl
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return handler(e)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/conceptnet5/web/conceptnet_web/web.py", line 174, in error_data_un
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return render_error(503, str(e))
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/conceptnet5/web/conceptnet_web/web.py", line 207, in render_error
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     'details': details
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/templating.py", line 133, in
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/jinja2/environment.py", line 869,
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return self.get_template(template_name_or_list, parent, globals)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/jinja2/environment.py", line 830,
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return self._load_template(name, self.make_globals(globals))
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/jinja2/environment.py", line 804,
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     template = self.loader.load(self, name, globals)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in l
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     source, filename, uptodate = self.get_source(environment, name)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/templating.py", line 57, in
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return self._get_source_fast(environment, template)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/templating.py", line 85, in
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     raise TemplateNotFound(template)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]: jinja2.exceptions.TemplateNotFound: error.html
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]: During handling of the above exception, another exception occurred:
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]: Traceback (most recent call last):
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/app.py", line 2000, in __cal
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return self.wsgi_app(environ, start_response)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/app.py", line 1991, in wsgi_
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     response = self.make_response(self.handle_exception(e))
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/app.py", line 1574, in handl
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return handler(e)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/conceptnet5/web/conceptnet_web/web.py", line 192, in internal_serv
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return render_error(500, '%s: %s' % (e.__class__.__name__, e))
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/conceptnet5/web/conceptnet_web/web.py", line 207, in render_error
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     'details': details
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/templating.py", line 133, in
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/jinja2/environment.py", line 869,
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return self.get_template(template_name_or_list, parent, globals)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/jinja2/environment.py", line 830,
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return self._load_template(name, self.make_globals(globals))
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/jinja2/environment.py", line 804,
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     template = self.loader.load(self, name, globals)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/jinja2/loaders.py", line 113, in l
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     source, filename, uptodate = self.get_source(environment, name)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/templating.py", line 57, in
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     return self._get_source_fast(environment, template)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:   File "/home/conceptnet/env/lib/python3.5/site-packages/flask/templating.py", line 85, in
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]:     raise TemplateNotFound(template)
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]: jinja2.exceptions.TemplateNotFound: error.html
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]: [pid: 13582|app: 0|req: 1/1] 127.0.0.1 () {32 vars in 362 bytes} [Mon Apr 16 18:24:44 2018]
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]: announcing my loyalty to the Emperor...
Apr 16 18:24:45 ip-172-31-88-7 uwsgi[13569]: Mon Apr 16 18:24:45 2018 - [emperor] vassal conceptnet-web.ini is now loyal

It looks like it can't find the templates, which is weird, because it works in the localhost case. Any tips or ideas what is wrong?

**Comment by rolisz** [comment]
So, I solved the issue by switching to the master branch. By default, it was on the `json-ld-upgrade` branch. If I run the `puppet-apply.sh` script, it switches back to `json-ld-upgrade` and stops working again.

**Comment by rspeer** [comment]
Oh, thanks for pointing that out.

I'll work on making a new image that isn't out of sync in multiple ways.

**Comment by rspeer** [comment]
Try the new image "ConceptNet 5.6.0 image 2" (ami-080fad77).

**Comment by rspeer** [comment]
The image mentioned above didn't work, but this is resolved in the image "ConceptNet 5.6.2" (ami-ee169a91).
