### ISSUE TITLE
Cannot ssh into aws instance running conceptnet 5.6.0 image 2 

### ISSUE THREAD

**Issue by hooram** [commonsense/conceptnet5#196]
Following the steps outlined in https://github.com/commonsense/conceptnet5/wiki/Running-your-own-copy, I cannot ssh into my ec2 instance running the conceptnet ami. The instance has a public ip, and the security group is set up correctly too. Here is the output of ssh when I try connecting. I also chmod 400 the keyfile.

```
OpenSSH_7.2p2 Ubuntu-4ubuntu2.4, OpenSSL 1.0.2g  1 Mar 2016
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to INSTANCE_PUBLIC_IP [INSTANCE_PUBLIC_IP] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file MY_KEY.pem type -1
debug1: key_load_public: No such file or directory
debug1: identity file MY_KEY.pem-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.4
debug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.4 pat OpenSSH* compat 0x04000000
debug1: Authenticating to INSTANCE_PUBLIC_IP:22 as 'ubuntu'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:MIStZCMh3nHBRy/LxQGRMoJS8QRA9VYwlsOWR+/UIoE
debug1: Host 'INSTANCE_PUBLIC_IP' is known and matches the ECDSA host key.
debug1: Found key in /home/MY_LOCAL_USERNAME/.ssh/known_hosts:59
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: MY_KEY.pem
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
Permission denied (publickey).
```

Could this have to do with some left over configuration from when the AMI was made? Any pointers would be appreciated.

Cheers!

**Comment by arun63** [comment]
It would be good if the community addresses this issues as early as possible.
In the meanwhile, I have moved to conceptnet 5.6.0 AMI released last year.

**Comment by rspeer** [comment]
Are you sure that `MY_KEY.pem` is the key that you configured when you launched the server? (You do this on the last screen, the one where you have to acknowledge that you're locked out of the server if you don't have or download the key.)

I'm launching another copy right now with my key, and I'll make sure I can log in.

**Comment by rspeer** [comment]
Nope, you're right! I can't use the image either (except the copy of it that I already have running). Something in cloud-init is going wrong.

**Comment by rspeer** [comment]
Thanks for finding out that the image didn't work. I created and tested a new image, ConceptNet 5.6.2 (ami-ee169a91) -- let me know if this one works for you.

**Comment by arun63** [comment]
Yes. Image (ami-ee169a91) is working now. 

Thanks for fixing it quickly.
