### ISSUE TITLE
ConceptNet statistics 

### ISSUE THREAD

**Issue by danyaljj** [commonsense/conceptnet5#209]
Hi there, I am after of a few statistics to understand the graph structure of the knowledge graph in ConceptNet. I was wondering you already have these. 

- Average node degree 
- Avg in-degree 
- Avg out-degree 
- Max in-degree 
- Max out-degree 
- Length of the longest path 
- The average length of paths 
- The median length of paths 
- Number of edges

**Comment by jlowryduda** [comment]
We keep some [language stats](https://github.com/commonsense/conceptnet5/wiki/Languages) around, but not the numbers you're after. You can download the edges [here](https://github.com/commonsense/conceptnet5/wiki/Downloads). Please report back once you get your answers, I'd be very interested in these as well.
