### ISSUE TITLE
 Error: No such command "propagate"

### ISSUE THREAD

**Issue by sauveer** [commonsense/conceptnet5#211]
Hi, I am running the build.sh on the latest commit and it gave me the below error. Any help is appreciated.

rule propagate:
    input: data/assoc/assoc.csv, data/vectors/numberbatch-retrofitted.h5
    output: data/vectors/numberbatch-biased.h5.shard0, data/vectors/numberbatch-biased.h5.shard1, data/vectors/numberbatch-biased.h5.shard2, data/vectors/numberbatch-biased.h5.shard3, data/vectors/numberbatch-biased.h5.shard4, data/vectors/numberbatch-biased.h5.shard5
    jobid: 24
    resources: ram=24

Usage: cn5-vectors [OPTIONS] COMMAND [ARGS]...

Error: No such command "propagate".

**Comment by rspeer** [comment]
We added the sub-command "propagate" to the `cn5-vectors` command-line tool, so you need to reinstall it. In the root of the conceptnet5 repository, you should run:

    pip install -e .

or:

    python setup.py develop

The commands are approximately the same, and the best one to run would be whichever one you ran before.

**Comment by sauveer** [comment]
I ran the python the command and it did something but it still didn't resolve the issue :(

<code>
sopra@slnxdigtnbot02:~/conceptnet5$ sudo python3 setup.py develop
running develop
running egg_info
writing entry points to ConceptNet.egg-info/entry_points.txt
writing requirements to ConceptNet.egg-info/requires.txt
writing dependency_links to ConceptNet.egg-info/dependency_links.txt
writing ConceptNet.egg-info/PKG-INFO
writing top-level names to ConceptNet.egg-info/top_level.txt
reading manifest file 'ConceptNet.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ConceptNet.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.5/dist-packages/ConceptNet.egg-link (link to .)
ConceptNet 5.6.3 is already the active version in easy-install.pth
Installing cn5-convert script to /usr/local/bin
Installing cn5-db script to /usr/local/bin
Installing cn5-read script to /usr/local/bin
Installing cn5-vectors script to /usr/local/bin
Installing cn5-build script to /usr/local/bin

Installed /home/sopra/conceptnet5
Processing dependencies for ConceptNet==5.6.3
Searching for marisa-trie==0.7.5
Best match: marisa-trie 0.7.5
Adding marisa-trie 0.7.5 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for psycopg2-binary==2.7.4
Best match: psycopg2-binary 2.7.4
Adding psycopg2-binary 2.7.4 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for ordered-set==2.0.2
Best match: ordered-set 2.0.2
Adding ordered-set 2.0.2 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for xmltodict==0.11.0
Best match: xmltodict 0.11.0
Adding xmltodict 0.11.0 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for wordfreq==2.0.1
Best match: wordfreq 2.0.1
Adding wordfreq 2.0.1 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for langcodes==1.4.1
Best match: langcodes 1.4.1
Adding langcodes 1.4.1 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for numpy==1.14.3
Best match: numpy 1.14.3
Adding numpy 1.14.3 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for msgpack-python==0.5.6
Best match: msgpack-python 0.5.6
Adding msgpack-python 0.5.6 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for ftfy==5.3.0
Best match: ftfy 5.3.0
Adding ftfy 5.3.0 to easy-install.pth file
Installing ftfy script to /usr/local/bin

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for requests==2.18.4
Best match: requests 2.18.4
Adding requests 2.18.4 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for click==6.7
Best match: click 6.7
Adding click 6.7 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for snakemake==5.1.4
Best match: snakemake 5.1.4
Adding snakemake 5.1.4 to easy-install.pth file
Installing snakemake-bash-completion script to /usr/local/bin
Installing snakemake script to /usr/local/bin

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for regex==2018.2.21
Best match: regex 2018.2.21
Adding regex 2018.2.21 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for msgpack==0.5.6
Best match: msgpack 0.5.6
Adding msgpack 0.5.6 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for wcwidth==0.1.7
Best match: wcwidth 0.1.7
Adding wcwidth 0.1.7 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Adding chardet 3.0.4 to easy-install.pth file
Installing chardetect script to /usr/local/bin

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for idna==2.6
Best match: idna 2.6
Adding idna 2.6 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for urllib3==1.22
Best match: urllib3 1.22
Adding urllib3 1.22 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for certifi==2018.4.16
Best match: certifi 2018.4.16
Adding certifi 2018.4.16 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for docutils==0.14
Best match: docutils 0.14
Adding docutils 0.14 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for jsonschema==2.6.0
Best match: jsonschema 2.6.0
Adding jsonschema 2.6.0 to easy-install.pth file
Installing jsonschema script to /usr/local/bin

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for Jinja2==2.10
Best match: Jinja2 2.10
Adding Jinja2 2.10 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for appdirs==1.4.3
Best match: appdirs 1.4.3
Adding appdirs 1.4.3 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for ratelimiter==1.2.0.post0
Best match: ratelimiter 1.2.0.post0
Adding ratelimiter 1.2.0.post0 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for ConfigArgParse==0.13.0
Best match: ConfigArgParse 0.13.0
Adding ConfigArgParse 0.13.0 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for networkx==2.1
Best match: networkx 2.1
Adding networkx 2.1 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for datrie==0.7.1
Best match: datrie 0.7.1
Adding datrie 0.7.1 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for wrapt==1.10.11
Best match: wrapt 1.10.11
Adding wrapt 1.10.11 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for PyYAML==3.12
Best match: PyYAML 3.12
Adding PyYAML 3.12 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for MarkupSafe==1.0
Best match: MarkupSafe 1.0
Adding MarkupSafe 1.0 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Searching for decorator==4.3.0
Best match: decorator 4.3.0
Adding decorator 4.3.0 to easy-install.pth file

Using /home/sopra/.local/lib/python3.5/site-packages
Finished processing dependencies for ConceptNet==5.6.3
sopra@slnxdigtnbot02:~/conceptnet5$ cn5-vectors
Usage: cn5-vectors [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  compare_embeddings   The `input_filenames` are files that can be...
  comparison_graph     Convert a table of evaluation results into a...
  convert_fasttext
  convert_glove
  convert_polyglot
  convert_word2vec
  debias               Modify a frame to attempt to remove biases...
  evaluate             Evaluate a frame on word similarity and...
  evaluate_analogies   Evaluate a frame on analogy datasets: SAT,...
  evaluate_bias        Measure bias in a given frame.
  evaluate_raw         Evaluate a frame on word similarity tasks.
  evaluate_wordsim     Evaluate a frame on word similarity tasks.
  export_background
  export_text          Export a frame to a fastText-style text file.
  filter_word_vectors  Get embeddings for the words in...
  intersect            Combine the vector knowledge contained in...
  join_retrofit        Join parts of a retrofitted frame.
  miniaturize          Save a smaller version of a frame, which...
  retrofit             Run retrofit, operating on a part of a frame...
sopra@slnxdigtnbot02:~/conceptnet5$
</code>

**Comment by sauveer** [comment]
Hi,

I upgraded my pip and then tried. It works now :) Many Thanks for the help.
