### ISSUE TITLE
Snakefile: wrong cn5-vectors options 

### ISSUE THREAD

**Issue by gyankos** [commonsense/conceptnet5#220]
while running Snakemake, I got this error:

```
Error in job retrofit while creating output files data/vectors/fasttext-opensubtitles-retrofit.h5.shard0, data/vectors/fasttext-opensubtitles-retrofit.h5.shard1, data/vectors/fasttext-opensubtitles-retrofit.h5.shard2, data/vectors/fasttext-opensubtitles-retrofit.h5.shard3, data/vectors/fasttext-opensubtitles-retrofit.h5.shard4, data/vectors/fasttext-opensubtitles-retrofit.h5.shard5.
RuleException:
CalledProcessError in line 669 of /media/giacomo/3844311f-c5bc-4422-b67c-3e26e796c95d/conceptnet5/Snakefile:
Command 'cn5-vectors retrofit -s 6 data/vectors/fasttext-opensubtitles.h5 data/assoc/reduced.csv data/vectors/fasttext-opensubtitles-retrofit.h5' returned non-zero exit status 2
```

This error was solved by changing the -s option with -n.

Similar error happens with ``join_retrofit -s``. Bug solved by changing such arguments with ``join_shard_files -n`` within the Snakefile

**Comment by luminoso-beaudoin** [comment]
You may have an out of date Snakefile.  Recently the cn5-vectors join_retrofit command was replaced by cn5-vectors join_shard_files, and the -s (number of shards) option to cn5-vectors retrofit and join_shard_files was renamed -n, but the Snakefile was updated to reflect those changes.  Can you check to make sure that your Snakefile is from commit 08888e90288d8435af8688cf791f9be9da2e8b8d (dated 2018/05/22) or later?

**Comment by gyankos** [comment]
I suppose that I copy-pasted the old Snakefile I had into a newer project clone, so I think that that was my falut.

p.s. Is there a better option to ask for advices/suggestions when I'm not sure that my problem must be strictly considered as an Issue? Thanks for your assistance.

**Comment by luminoso-beaudoin** [comment]
No worries about creating an issue, but as it seems there is no change to the code required I will mark this as closed.  Besides making issues you can also post to the Gitter chat room for ConceptNet at <https://gitter.im/commonsense/conceptnet5>.
