### ISSUE TITLE
Caching in conceptnet5/vectors/query.py doesnt take into account the include_neighbors flag

### ISSUE THREAD

**Issue by tolomaus** [commonsense/conceptnet5#221]
Just wanted to report a small issue I noticed while playing around with the vectors:
```
vspace.get_vector("/c/en/customer_experience", include_neighbors=False)
vspace.get_vector("/c/en/customer_experience", include_neighbors=True)
```
returns twice a zero vector, while running the last line in a new ipython session:
```
vspace.get_vector("/c/en/customer_experience", include_neighbors=True)
```
returns a non-zero vector

**Comment by rspeer** [comment]
Thanks for discovering this! It's fixed by #222, which is now merged into the master branch.
