### ISSUE TITLE
merge_intersect should be able to run in 32 GB of RAM

### ISSUE THREAD

**Issue by sayak1711** [commonsense/conceptnet5#224]
I installed conceptnet using the puppet method on Ubuntu 16.04.
Then I followed all the steps sequentially and ran the build process. It however failed at 97%.
**Specs:**
i7 8th gen 8 core processor
32GB RAM

**Error Message:**
/bin/bash: line 1: 17311 Killed                  cn5-vectors intersect data/vectors/crawl-300d-2M-retrofit.h5 data/vectors/w2v-google-news-retrofit.h5 data/vectors/glove12-840B-retrofit.h5 data/vectors/fasttext-opensubtitles-retrofit.h5 data/vectors/numberbatch-biased.h5 data/vectors/intersection-projection.h5
    [Tue Aug 28 19:52:05 2018]
    Error in rule merge_intersect:
        jobid: 33
        output: data/vectors/numberbatch-biased.h5, data/vectors/intersection-projection.h5

RuleException:
CalledProcessError in line 665 of /home/conceptnet/conceptnet5/Snakefile:
Command ' set -euo pipefail;  cn5-vectors intersect data/vectors/crawl-300d-2M-retrofit.h5 data/vectors/w2v-google-news-retrofit.h5 data/vectors/glove12-840B-retrofit.h5 data/vectors/fasttext-opensubtitles-retrofit.h5 data/vectors/numberbatch-biased.h5 data/vectors/intersection-projection.h5 ' returned non-zero exit status 137
  File "/home/conceptnet/conceptnet5/Snakefile", line 665, in __rule_merge_intersect
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
[Tue Aug 28 22:44:13 2018]
Finished job 11.
437 of 451 steps (97%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/conceptnet/conceptnet5/.snakemake/log/2018-08-28T155815.852935.snakemake.log

**Comment by rspeer** [comment]
Exit code 137 means the process was killed, presumably due to running out of memory. That lets me know what the real issue is here -- I'll change the title accordingly.

**Comment by rspeer** [comment]
Are you sure your computer wasn't using a lot of RAM for other things? I just tried running that exact step with a limit of 30 GB, and it worked.

Alternatively, have you added data to ConceptNet that would enlarge the vocabulary of this step and cause it to require more memory?

**Comment by rspeer** [comment]
I've tested the `merge_intersect` step in an environment where it only has 24 GB of memory allocated to it. It works.

I think it's relevant that when your process dies with exit code 137, it's not just that the process can't allocate memory -- it's that the processes on your OS as a whole have _over_-allocated memory, and have surprised the OS by insisting on actually using it. It's rather analogous to an overbooked airplane. When this happens on Linux, Linux will kill high-memory processes arbitrarily.

My recommendation is to re-run the build script (it should pick up where it left off) with fewer other things running on the same computer.
