### ISSUE TITLE
Downloading is slowly, would you please upload it to google driver?

### ISSUE THREAD

**Issue by loveJasmine** [commonsense/conceptnet5#225]
https://zenodo.org/record/1165009/files/conceptnet-raw-data-5.6.zip

**Comment by rspeer** [comment]
Google Drive does not support sharing 23 GB files.

Also, I tested the download; Zenodo appears to be working fine and sending the file at about 2 MB/s, at which rate it takes about 3 hours to download. This tells me that the bottleneck is on your end and would not be solved by Google Drive. At any reasonable download speed you should be able to download it in much less time than it takes to implement another download method.

**Comment by loveJasmine** [comment]
I can downloading from google driver on 3M/s

but for https://zenodo.org/record/1165009/files/conceptnet-raw-data-5.6.zip
only <10K/s, and even worse, it looks it does't support "wget -c"

**Comment by rspeer** [comment]
I'm still kind of surprised Zenodo data isn't getting to you fast enough. Wherever you are, it doesn't seem like it's just a matter of distance; Zenodo is hosted at CERN in Switzerland and I'm getting the data very quickly in Boston. But it can't get to you as fast as Google Drive does. Is this what happens when we don't have net neutrality?

I would be open to suggestions for other places to mirror the ConceptNet data, but I would be looking for other places that offer free hosting for research, not places that require a monthly fee, and not places that don't want to deal with multi-gigabyte files.

**Comment by rspeer** [comment]
Okay I see the problem.

Unfortunately, I doubt that I would be able to mirror the data inside your country, any more than you can easily get the data from Zenodo. I know that groups such as Yuanfudao Research have done some excellent work with ConceptNet, so there must be some way to get the data, but I don't know what it is.

I suppose that for the same reason you wouldn't be able to use an Amazon AMI that's in the us-east-1 region, right? That's another way that people are able to build ConceptNet.

**Comment by loveJasmine** [comment]
Yuanfudao is a commercial company.
thanks your information

**Comment by loveJasmine** [comment]
With some VPN, I can reach more than 2MB/s downloading, but it always inturrupt in the middle, an it cann't resume

ub16hp@UB16HP:~$ wget -c https://zenodo.org/record/1165009/files/conceptnet-raw-data-5.6.zip
--2018-09-30 11:21:39--  https://zenodo.org/record/1165009/files/conceptnet-raw-data-5.6.zip
Connecting to 127.0.0.1:44153... connected.
Proxy request sent, awaiting response... 200 OK
Length: 23909242585 (22G) [application/octet-stream]
Saving to: ‘conceptnet-raw-data-5.6.zip’

conceptnet-raw-data-5.6.zip                          6%[======>                                                                                                          ]   1.55G  3.30MB/s    in 11m 40s 

2018-09-30 11:34:21 (2.27 MB/s) - Connection closed at byte 1668249470. Retrying.

--2018-09-30 11:34:22--  (try: 2)  https://zenodo.org/record/1165009/files/conceptnet-raw-data-5.6.zip
Connecting to 127.0.0.1:44153... connected.
Unable to establish SSL connection.
ub16hp@UB16HP:~$
