### ISSUE TITLE
Unix setup successful but issues with the output

### ISSUE THREAD

**Issue by shikhar26** [commonsense/conceptnet5#226]
we have been able to run all steps of the ConceptNet build process, and it works.
But, the output data does not provide anything but an empty string for "rel.label".
Can someone please assist?

e.g.
**Output:**
"rel": {
        "@id": "/r/RelatedTo",
        "@type": "Relation",
        "label": ""
 }

**expected:**
"rel": {
        "@id": "/r/RelatedTo",
        "@type": "Relation",
        "label": "RelatedTo"
 }

Please suggest if I missed something in the build process, and how it can be fixed?

**Comment by rspeer** [comment]
Thanks for the bug report -- I tracked it down and created a PR to fix it.
