### ISSUE TITLE
if I use 'snakemake --resources 'ram=12' -j 2 '   (set ram=12 but not 16), does it can run build.sh  on a 16G memory laptop 

### ISSUE THREAD

**Issue by loveJasmine** [commonsense/conceptnet5#229]

**Comment by rspeer** [comment]
No, you need 24 GB of available RAM, because of a couple of individual steps (merge_intersect and debias) that require that much RAM to run.

Snakemake can be used to plan which processes to run at the same time, but it can't actually cause a particular step to need less RAM.
