### ISSUE TITLE
how can i build a Chinese version of conceptnet?

### ISSUE THREAD

**Issue by loveJasmine** [commonsense/conceptnet5#232]
here is file:
ub16hp@UB16HP:~/ub16_prj/conceptnet5$ wc -l chineseconceptnet.csv 
624805 chineseconceptnet.csv

each line like:
/a/[/r/AtLocation/,/c/zh/文章/,/c/zh/批踢踢/]   /r/AtLocation   /c/zh/文章      /c/zh/批踢踢    {"dataset": "/d/conceptnet/4/zh", "license": "cc:by/4.0", "sources": [{"activity": "/s/activity/ptt/petgame", "contributor": "/s/contributor/petgame/pet_12498"}, {"activity": "/s/activity/ptt/petgame", "contributor": "/s/contributor/petgame/pet_4107"}], "surfaceEnd": "文章", "surfaceStart": "批踢踢", "surfaceText": "[[批踢踢]] 有 [[文章]]。", "weight": 2.0}
/a/[/r/AtLocation/,/c/zh/文章/,/c/zh/網誌/]     /r/AtLocation   /c/zh/文章      /c/zh/網誌      {"dataset": "/d/conceptnet/4/zh", "license": "cc:by/4.0", "sources": [{"activity": "/s/activity/ptt/petgame", "contributor": "/s/contributor/petgame/pet_19534"}], "surfaceEnd": "文章", "surfaceStart": "網誌", "surfaceText": "你可以在 [[網誌]] 找到 [[文章]]。", "weight": 1.0}
/a/[/r/AtLocation/,/c/zh/文章/,/c/zh/網路上/]   /r/AtLocation   /c/zh/文章      /c/zh/網路上    {"dataset": "/d/conceptnet/4/zh", "license": "cc:by/4.0", "sources": [{"activity": "/s/activity/ptt/petgame", "contributor": "/s/contributor/petgame/pet_27304"}], "surfaceEnd": "文章", "surfaceStart": "網路上", "surfaceText": "[[網路上]] 有 [[文章]]。", "weight": 1.0}

can i use this file 'chineseconceptnet.csv ' to build a Chinese version of conceptnet??

**Comment by rspeer** [comment]
GitHub Issues is not a good place for Q&A. Please ask a more detailed question on the [Gitter chat](https://gitter.im/commonsense/conceptnet5).
