### ISSUE TITLE
Web API Rate Limiting

### ISSUE THREAD

**Issue by bhylak** [commonsense/conceptnet5#242]
What is the maximum number of requests per second/minute/hour? After making 5-10 in a second, it hangs for 30-60 seconds.

**Comment by rspeer** [comment]
The maximum rate on the relatedness API (which is more resource-consuming) is intended to be 60 per minute.

Can you get 60 requests in a minute from a fresh start? If it can't serve that many requests, I may need to lower the limit to preserve availability.

**Comment by bhylak** [comment]
3 days ago I was having these timeouts using any endpoint, even via the web API. 

As of yesterday, status seems to be nominal from my end. My application makes around 50 relatedness requests per minute, while it's actively being used.

I'd love to get my own ec2 instance up so I can stop bombarding you all with requests to that end point. (#243 -- can this endpoint be used on medium tier?)

**Comment by rspeer** [comment]
It is certainly true that ConceptNet 5.6 wasn't keeping up with the rate limits it allowed. ConceptNet 5.7 should be able to deal with more requests.
