### ISSUE TITLE
Web API Bad Gateway

### ISSUE THREAD

**Issue by jmacunha** [commonsense/conceptnet5#244]
I am using the web API for a while now. Lately I have been getting these "502 Bad Gateway". Is this something that is being solved?

Thanks

**Comment by TechyMitch1** [comment]
I'm getting 502's today as well.

**Comment by crystal-butler** [comment]
I've never used the web API before, but I just tried setting up my own ConceptNet instance on AWS and am getting the "502 Bad Gateway" error there as well. From /var/log/nginx/error.log, the error that gets generated when trying to connect to the web server looks like:

2019/01/28 01:45:05 [error] 5380#5380: *25 upstream prematurely closed connection while reading response header from upstream, client: 127.0.0.1, server: conceptnet.io, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/conceptnet/uwsgi/run/uwsgi-conceptnet-web.sock:", host: "www.conceptnet.localhost"

The error is the same when connecting remotely, except for the client IP. This seems like it might be a problem with the way uwsgi or nginx is configured, but I've never worked with either before and haven't had any luck finding similar examples, so any help would be appreciated.

**Comment by drchrisscheier** [comment]
same problem for me !

**Comment by rspeer** [comment]
I tried restarting it last night. It was up for a moment. Now it's down again.

Unfortunately I can't find anything in the logs. uwsgi just... goes away. I don't understand what would have changed to make this start happening, but I'm looking into it.

**Comment by rspeer** [comment]
Updates in: https://gitter.im/commonsense/conceptnet5

**Comment by rspeer** [comment]
I put up a hotfix for the queries that were making the API grind to a halt and become unavailable. The next step is to fix the issue in a correct and less ad-hoc way.

**Comment by jmacunha** [comment]
The web API is down again. Any way of solving this?

**Comment by rspeer** [comment]
It's back now (because I put the old version back). The "less ad-hoc" fix to these slow queries apparently wasn't enough.
