### ISSUE TITLE
Web API - Filter by Language

### ISSUE THREAD

**Issue by hagt** [commonsense/conceptnet5#251]
I did not use the api for quite a while, now I'm missing a feature that was present in previous versions of the api.

Concept lookup and concept query do not allow to filter by language. I would be happy if both types of queries would support the filter parameter (as it is already present for the related query).

Also, filtering as suggested in this issue, does not work:
https://github.com/commonsense/conceptnet5/issues/89

E.g., this query still returns edges to non-English nodes:
http://api.conceptnet.io/query?node=/c/en/doctor&other=/c/en&offset=0&limit=100

**Comment by rspeer** [comment]
Filtering for `/c/en` was one of the time-consuming queries that we had to do a quick and imperfect workaround for on 5.6 so that the API would stay up. It's fixed in 5.7.
