### ISSUE TITLE
How to extract the concepts and its relations ?

### ISSUE THREAD

**Issue by Lapis-Hong** [commonsense/conceptnet5#259]
I wonder how to achieve this core task, it seems the code if only for building for existed data, not for extraction? Would you please explain the logic for extracting relations from raw text data?

**Comment by rspeer** [comment]
We have a lot of data sources and the way of converting them into ConceptNet-like graph data varies for each one. Please join us [on Gitter](https://gitter.im/commonsense/conceptnet5) to discuss this further, as Github Issues isn't a format designed for Q&A.
