### ISSUE TITLE
Some lines of Portuguese CSV data incorrectly formatted

### ISSUE THREAD

**Issue by jchien14** [commonsense/conceptnet5#28]
It appears that some lines of Portuguese data in the CSV files are incorrectly formatted (they have early and extra right brackets). This was only observed for Portuguese data when parsing through every file.

Example ones in part_01.csv are:

<pre>
/a/[/r/AtLocation/,/c/pt/bicho_de_goiaba]/,/c/pt/pé_de_goiaba/]    /r/AtLocation   /c/pt/bicho_de_goiaba]  /c/pt/pé_de_goiaba /ctx/all    2.584962500721156   /or/[/and/[/s/activity/omcs/csamoa4_self-rating/,/s/contributor/omcs/dimiguel/]/,/and/[/s/activity/omcs/vote/,/s/contributor/omcs/filipeaoki/]/,/and/[/s/activity/omcs/vote/,/s/contributor/omcs/ivonegodoi/]/,/and/[/s/activity/omcs/vote/,/s/contributor/omcs/kis/]/] /e/e3bf73c9389d4cb7d6e97a2a2a866f6dff832f0a /d/conceptnet/4/pt  *Uma coisa que você pode encontrar em um(a) [[pé de goiaba]] é um(a) [[bicho de goiaba]]].
/a/[/r/AtLocation/,/c/pt/velho]/,/c/pt/praça_pública/]    /r/AtLocation   /c/pt/velho]    /c/pt/praça_pública   /ctx/all    1.5849625007211563  /and/[/s/activity/omcs/csamoa4_self-rating/,/s/contributor/omcs/chocolatra_cg/] /e/4b5c4fff87fe7254de329e0895a8a211a78ad68d /d/conceptnet/4/pt  *Uma coisa que você pode encontrar em um(a) [[praça pública]] é um(a) [[velho]]].
/a/[/r/AtLocation/,/c/pt/mofo]/,/c/pt/teto_com_goteiras/]   /r/AtLocation   /c/pt/mofo] /c/pt/teto_com_goteiras /ctx/all    1.5849625007211563  /and/[/s/activity/omcs/csamoa4_self-rating/,/s/contributor/omcs/_kamikaze_/]    /e/f40f1d8d86868cb2b63d1256c81f80194ca51774/d/conceptnet/4/pt   *Uma coisa que você pode encontrar em um(a) [[teto com goteiras]] é um(a) [[mofo]]].
</pre>

**Comment by rspeer** [comment]
This was fixed at some point and I neglected to close the bug.
