### ISSUE TITLE
Evaluation code Snakemake

### ISSUE THREAD

**Issue by JohannaOm** [commonsense/conceptnet5#284]
Hello,
what code is used for the evaluation to generate the evaluation.h5 file?
Is it located in conceptnet5/vectors/evaluation?
I'm trying to slightly modify the wordsim.py file to get information about the similarity scores for each pair of words and not just the correlation, but snakemake still seems to use the original code and doesn't see my changes. 
Am I working with a wrong file ? 
Does the rule 'rule compare_embeddings:' use this code (conceptnet5/vectors/evaluation) or is other code executed?

**Comment by rspeer** [comment]
The first thing I'd want to check is, is the version of the ConceptNet code you edited the one that's installed in your Python environment? You can make sure of this with `pip install -e .` in the top-level conceptnet5 directory. The Snakefile is running whatever `cn5-vectors` command is installed.

**Comment by JohannaOm** [comment]
I did not install the ConceptNet code, I just pulled it.
I simply downloaded and unzipped the repository from gihub and executed it on the server. I created a docker container with all the requirements given in tutorial and gave it access to the downloaded ConceptNet repository to create ConceptNet this way. 
I made some changes in conceptnet5/vectors/evaluation/wordsim.py and tried to create (rerun) the evaluation with :
`snakemake -R compare_embeddings`

But there were no changes. Snakemake seems to run the old code.

Does Snakemake download additional Conceptnet code?

Sorry if it's a trivial problem.

**Comment by JohannaOm** [comment]
The problem was that I did not have that much experience with the docker :)
As you suspected, the problem was caused by the execution of the old code version.
When I build the image, I run the following command:
` pip3 install -e '/work/[vectors]'`. 
So all commands were saved from the old code. 
If you are working with Docker and you want a new code to run, you have to update all commands.
