### ISSUE TITLE
api.conceptnet.io : Internal server error

### ISSUE THREAD

**Issue by anastasia-zhukova** [commonsense/conceptnet5#292]
Hi, 
When trying to reach api, e.g., with "http://api.conceptnet.io/c/en/example", I got the error 500: 

{
  "@context": [
    "http://api.conceptnet.io/ld/conceptnet5.7/context.ld.json"
  ],
  "error": {
    "details": "Internal server error",
    "status": 500
  },
  "version": "5.8.1"
}

Will the server be available again soon? Thanks.

**Comment by rspeer** [comment]
Thanks for letting us know. The server should be back to working now.
