### ISSUE TITLE
Internal server error while accessing web api

### ISSUE THREAD

**Issue by kartik7511** [commonsense/conceptnet5#299]
I am trying to access the web API of conceptnet. But getting internal server error instead
<img width="1434" alt="Screenshot 2020-11-19 at 4 21 31 PM" src="https://user-images.githubusercontent.com/30037205/99656872-7069db00-2a83-11eb-98a5-a7195c3e02ab.png">

**Comment by henningsmith** [comment]
The server was experiencing database connection issues and restarting the conceptnet service resolved it. Please try again.

**Comment by kartik7511** [comment]
Works now. Thanks.

**Comment by jlowryduda** [comment]
@kartik7511 If you are hitting API a lot, please use `sleep()` from time to time to give the database some time to catch a breath :)
