### ISSUE TITLE
Filter based on Language

### ISSUE THREAD

**Issue by lalchand-pandia** [commonsense/conceptnet5#302]
I want to get results with relation=IsA and language preference is english.
So, I am using a python request:
response = requests.get('http://api.conceptnet.io/query?rel=/r/IsA&lang=en')
Still, I am getting results in Japanese.

**Comment by rspeer** [comment]
`lang` isn't an API parameter. The query you want is:

http://api.conceptnet.io/query?rel=/r/IsA&start=/c/en&end=/c/en
