### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by C0c0aG33k** [commonsense/conceptnet5#304]
Hello. This is probably not the right place (It has been mentioned on gitter too), but the server at http://www.conceptnet.io/ has been returning the following error for at least a week:

InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by henningsmith** [comment]
Thanks for the notification - I have restarted the services and it is working now again. Can you please confirm that it is working for you too?

**Comment by C0c0aG33k** [comment]
Yep, it works now. Thank you @henningsmith !

**Comment by alanas1103** [comment]
Hello. Coceptnet.io gives this message again: 
InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by rtbs-dev** [comment]
I just ran into this as well
