### ISSUE TITLE
Internal Server Error 500 while accessing the API

### ISSUE THREAD

**Issue by Naushad9458** [commonsense/conceptnet5#313]
[
<img width="1138" alt="Screenshot 2021-11-15 at 12 52 13" src="https://user-images.githubusercontent.com/12751308/141785425-6c48b699-22cd-4d28-99e1-e7e81ec5c165.png">
](url)

**Comment by zhanwenchen** [comment]
Same problem @rspeer

**Comment by giovanniwdc** [comment]
The same here.

**Comment by xiangyu-peng** [comment]
SAME

**Comment by tae898** [comment]
same here :'(

I lost my common sense now

**Comment by SamBahrami** [comment]
Yeah, same issue here. 500 error when I try to access something like ```https://api.conceptnet.io/c/en/example```

**Comment by jcsun-00** [comment]
The same here.

**Comment by armandhuet** [comment]
Same here. Is there a workaround or do we have to wait until it is fixed?

**Comment by amirouche** [comment]
The workaround is to load the `.csv` into your own database on-premise or on your development setup.

**Comment by zhanwenchen** [comment]
> The workaround is to load the `.csv` into your own database on-premise or on your development setup.

Which .csv? I was able to build and deploy conceptnet5 locally but it'll be good to have an alternative as well.

**Comment by amirouche** [comment]
In the wiki, in the download page there is link to the csv : https://github.com/commonsense/conceptnet5/wiki/Downloads

**Comment by anam294** [comment]
Hello, 500 internal server error is still occurring on public API on http://api.conceptnet.io/c/en/cat. 
Any idea when this will be resolved?

**Comment by rspeer** [comment]
I, very unfortunately, don't have control over conceptnet.io anymore (it still belongs to Luminoso), but I've e-mailed Luminoso about it and I believe they fixed it.

**Comment by tae898** [comment]
In case people are still interested in running conceptnet locally on docker, take a look at this: https://github.com/tae898/conceptnet5
