### ISSUE TITLE
Internal server error: 500

### ISSUE THREAD

**Issue by Rayckey** [commonsense/conceptnet5#331]
I'm afraid the infamous 500 error code has returned :( , cleared the buffer we usually used today and found that all of the queries returned with the same error code.

**Comment by KaiPoChang** [comment]
Same problem

**Comment by masterparser** [comment]
I am also having this problem, so I set up my own copy using these instructions:
https://github.com/commonsense/conceptnet5/wiki/Running-your-own-copy

Running your own copy will require running an AWS EC2 instance. The suggested t2.medium instance currently costs $0.0464/hour and you will need to provision a 400 GB drive (General Purpose SSD (gp2)), which costs $0.10 per GB-month. To save on costs, I intend to keep my copy for only a few days and turn off the instance (just the compute part) at the end of the day.

**Comment by rspeer** [comment]
Last time I contacted ***@***.*** about this, they didn't even reply to me, but they did restart the process. I've just tried emailing them again.

**Comment by Rayckey** [comment]
It looks like conceptnet is now back online, likely thanks to @rspeer . I'll close the issues now
