### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by evilsizord** [commonsense/conceptnet5#34]
I'm getting an SQL Error when I try to query a concept ending with "/." 

Apparently this causing 500 internal server error on the API. For example:
http://conceptnet-api-1.media.mit.edu/data/5.3/search?rel=/r/IsA&end=/c/en/land/.&limit=20

I believe the offending line is
https://github.com/commonsense/conceptnet5/blob/master/conceptnet5/formats/sql.py#L228

And for me it was fixed by putting 'true' in quotes.

**Comment by roytseng-tw** [comment]
I encounter the same error with this functionality "/.", too.
I solve it by changing  conceptnet5/formats/sql.py 's complete_req sql string: true -> 1

**Comment by ashutoshideaphora** [comment]
Anyone found the solution for this?
