### ISSUE TITLE
[5.3] score attribute missing

### ISSUE THREAD

**Issue by TimDaub** [commonsense/conceptnet5#35]
Hi,

I just loaded version 5.3 on my server and what seems to be missing is the score attribute for every concept.
Because I highly need this attribute, I'd like to ask were it went as I can't seem to find it getting removed in one of the commits.

Is this a bug or did you remove it for some reason?
Also if it's not a bug, what can I use instead?
I need weighted links (scores)

**Comment by rspeer** [comment]
It looks like I neglected to mention this in the changelog until now. (I've
added it.)

The "score" attribute was always an artifact of Solr, and now that the data
isn't stored in Solr, that attribute doesn't appear anymore.

You should use the "weight" attribute instead. The "score" represented the
"weight" multiplied by Solr's built-in search weight, which was difficult
to define anyway.

**Comment by TimDaub** [comment]
Hi,

thanks for your quick response.
That solved my problem sufficiently.

Have a nice day.
