### ISSUE TITLE
URI queries depend on case of first letter, ground beef does not work

### ISSUE THREAD

**Issue by Concomitant** [commonsense/conceptnet5#58]
I noticed last night that queries seemed to distinguish unnecessarily between capitalized and non-capitalized versions of terms. I noticed this morning that it had change, with some terms that previously needed to be capitalized now needing to be lower case, and vice versa.

The example on the wiki: http://conceptnet5.media.mit.edu/data/5.4/uri?language=en&text=ground_beef
returns nothing as of this writing, and it is required to query
http://conceptnet5.media.mit.edu/data/5.4/uri?language=en&text=ground_Beef

to get a result.

**Comment by rspeer** [comment]
I'm seeing the opposite of what you're seeing. http://conceptnet5.media.mit.edu/data/5.4/uri?language=en&text=ground_beef is the one that works for me.

I wonder if the two API machines are running different code here, so changing the case is just changing which cached result you get.

**Comment by rspeer** [comment]
Hm, it's not different between the two machines. I don't know what's going on, in particular why some of the results would be returning a structure with 'edges' and 'numFound' at all.

**Comment by Concomitant** [comment]
Ground beef has switched back to needing to be lower case.

'level' doesn't seem to be working at all now :( http://conceptnet5.media.mit.edu/data/5.4/uri?language=en&text=ground_Beef

**Comment by Concomitant** [comment]
I mean "...&text=level"

**Comment by rspeer** [comment]
I think I see what's going on.

These URLs match multiple endpoints in the ConceptNet API. One endpoint believes you're asking for a URI, while another one incorrectly believes you're looking up a ConceptNet node named "uri".

I've been relying on Flask to route URLs in a priority order, and it seems that it doesn't anymore. Now it seems to depend on the ordering of things in a Python dictionary -- which is non-deterministic and changes every time a new process is started.

This is why it's changing with time and with the exact URL you put in.

I'll work on a fix.

**Comment by Concomitant** [comment]
Thanks a lot! Definitely reduces a lot of confusion on this end.

**Comment by rspeer** [comment]
I've released version 5.4.2 and updated the server. It seems fixed. Thanks for the bug report!
