### ISSUE TITLE
Not able to mount data to conceptnet_data in docker container

### ISSUE THREAD

**Issue by manasRK** [commonsense/conceptnet5#59]
I followed all the steps for the docker container, but all I get is INTERNAL SERVER ERROR,. And even when I tried the bash shell as shown here #57  , I was unable to see the mapped container folder 'conceptnet_data'.

Docker Info:
```
Client:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
Server:
 Version:      1.10.2
 API version:  1.22
 Go version:   go1.5.3
 Git commit:   c3959b1
 Built:        Mon Feb 22 21:37:01 2016
 OS/Arch:      linux/amd64
```

Command I ran to start the docker: 
`sudo docker run --privileged -p 127.0.0.1:10054:10054 --sig-proxy=false rspeer/conceptnet-web:5.4 -v /large-disk/conceptnet5.4/data:/conceptnet_data 
`
Please help me out !

**Comment by manasRK** [comment]
[UPDATE]

Even logging from `root` in the host machine doesn't help. Nor does explicitly creating a workinng directory in the container using `-w` flag.

Latest code to run the docker machine:

`sudo docker run -w /conceptnet_data  --privileged -p 127.0.0.1:10054:10054 rspeer/conceptnet-web:latest -v /large-disk/conceptnet5.4/data:/conceptnet_data`

**Comment by rspeer** [comment]
Can you get a shell inside your Docker container? See if the `/conceptnet_data` directory is actually there in the filesystem.

**Comment by manasRK** [comment]
Thanks for your reply !

Yes, I got a shell into the container. I tried `ls` in the shell, was unable to find the `/conceptnet_data` directory in it. I am new to docker, am I missing something here?

**Comment by rspeer** [comment]
A co-worker of mine helped out here. I actually gave the command in the wrong order. The `-v` and its argument needed to come *before* the image name, as the way it's written, it's just passing them as arguments to the ConceptNet web server.

So try something like this, possibly with the extra arguments you added if they're still necessary:

    sudo docker run -v /large-disk/conceptnet5.4/data:/conceptnet_data rspeer/conceptnet-web:5.4

Sorry for the inconvenience and I'll go update the wiki.

**Comment by manasRK** [comment]
Thanks, it works now !! Now, I can move on to test my hypotheses :)
