### ISSUE TITLE
Sorry. but i can run the docker image 'conceptnet-web:5.4' well

### ISSUE THREAD

**Issue by litterzhang** [commonsense/conceptnet5#60]
![2016-03-24 10-33-36](https://cloud.githubusercontent.com/assets/5362066/14006802/e45d53ea-f1ab-11e5-9595-ade86776b236.png)
is this ok ?

but when i open the url 'http://0.0.0.0:10054' in broswer.

![2016-03-24 10-35-30](https://cloud.githubusercontent.com/assets/5362066/14006835/272cf6ee-f1ac-11e5-8e91-0ecda32d468b.png)

what should i do?

**Comment by rspeer** [comment]
Replace "0.0.0.0" with "localhost" or "127.0.0.1".

"0.0.0.0" is a confusing Unix way to say "all addresses on this machine".
