### ISSUE TITLE
Description of software I am downloading is missing, is this an actual AI?

### ISSUE THREAD

**Issue by Yeti81** [commonsense/conceptnet5#62]
I came here after reading about advanced AI, I was hoping to put it to the test.

I can't see anything about what the software actually does, no real time information, it all looks like programming gibberish to me.

If I am the wrong place then I apologise, but is there anyway to talk to this AI by just downloading a package and installing the software or is this the intended software used to programme the AI from scratch?

Thanks in advance
Confused Yeti

**Comment by rspeer** [comment]
I'm curious what you read.

Sorry to disappoint you. This is not a chat-bot, it's one component you would use to program an AI system that understands what words mean.
