### ISSUE TITLE
ERROR on the build process conceptnet5

### ISSUE THREAD

**Issue by UUSR** [commonsense/conceptnet5#63]
Not created Ninja file that describes the process of building ConceptNet.

`~/conceptnet5$ python ninja.py`
  `File "ninja.py", line 458`
   ` print(ninja, file=open('build.ninja', mode='w'))`
   `                  ^`
`SyntaxError: invalid syntax`

**Comment by rspeer** [comment]
I'll need to see if this page fails to refer to the things you need to set
up first.

You need a Python 3 environment, and you need the ConceptNet code installed
in it. Your environment is Python 2.

**Comment by UUSR** [comment]
@rspeer Now I check:

`$ python --version`
`Python 2.7.6`
`$ python3 --version`
`Python 3.4.3`

**Comment by rspeer** [comment]
Okay -- did that solve your problem?
