### ISSUE TITLE
Differences between Docker images

### ISSUE THREAD

**Issue by nmstoker** [commonsense/conceptnet5#64]
Hello,
It may be obvious to others, but it seems a little unclear regarding the differences in the two Docker images - one seems to do everything and the other does the web.

Does that mean if I get the everything version I can easily switch it to also show the web-front end?

A little more colour would help out here (since I'm hesitant to "just have a go" given the resources needed :smile: )

Would be great if you could spell out a little more exactly what the differences are.

Many thanks,
Neil

**Comment by nmstoker** [comment]
Anybody?

**Comment by nmstoker** [comment]
I just went with the conceptnet-web one - it seems to work fine for basic API usage so far.  Unsure if I'm missing anything from the other one, but might as well close this now...

**Comment by jac2130** [comment]
I would love to know where the Dockerfiles and docker-compose scripts are located, so if one wants to modify things one can do that?  Are those somewhere publicly stored?

**Comment by rspeer** [comment]
This issue is from 3 years ago, and ConceptNet does not currently use Docker.

**Comment by jac2130** [comment]
I see, do you have some guidance for someone who would like to run your system in Docker containers?

**Comment by rspeer** [comment]
No I don't, and -- although you got around the message saying this by adding to an old issue -- GitHub Issues is not a Q&A site.
