### ISSUE TITLE
Is there any way to "run my own copy" on windows?

### ISSUE THREAD

**Issue by mosynaq** [commonsense/conceptnet5#65]
Hi.
As the title implies I want to run ConceptNet on Windows. But following the wiki didn't give me any success.
Is there any way to "run my own copy" on windows?

Thanks!

**Comment by rspeer** [comment]
Not that I know of, except that you could use a virtual machine through a
system such as Vagrant.

**Comment by mosynaq** [comment]
I wonder if  you know where I can download such a box for Windows?

**Comment by amirouche** [comment]
@mosynaq vagrant is a software that you download at https://www.vagrantup.com/downloads.html
