### ISSUE TITLE
Error while generating wiktionary data

### ISSUE THREAD

**Issue by sharmi** [commonsense/conceptnet5#67]
Hi,
    I am trying to build the data from start, replacing the original wiktionary data with the latest article.tgz file.
I have run 
make apsw

After running

make download

I have made the english wiktionary data switch.

Then I ran make and I get the following error.

cd /home/code/wordhunt/conceptnetmybuild/conceptnet5/conceptnet5/wiktparse && make en_parser.py
make[1]: Entering directory `/home/code/wordhunt/conceptnetmybuild/conceptnet5/conceptnet5/wiktparse'
grako -m en_wiktionary -w '' -o en_parser.py en_parser.ebnf
en_parser.ebnf(13:1) Expecting <word> :

^
word
name
rule
grammar
start
make[1]: **\* [en_parser.py] Error 1
make[1]: Leaving directory `/home/code/wordhunt/conceptnetmybuild/conceptnet5/conceptnet5/wiktparse'
make: **\* [/home/code/wordhunt/conceptnetmybuild/conceptnet5/conceptnet5/wiktparse/en_parser.py] Error 2

The en_parser.ebnf file is empty except for the top 'Do not edit this file' comment paragraph. I am using python3 and have installed nltk and pyyaml.  Is there anything else that I need to do?

**Comment by sharmi** [comment]
Running make {{basepath}}/wiktparse/en_parser.py after removing the empty .bnf files worked but I don't know how we got the empty bnf files in the first place

**Comment by rspeer** [comment]
Hm, that's odd. Was there a previous build that crashed with an error message? That's the most likely reason I can think of for empty bnf files.

Version 5.5 will shortly move Wiktionary parsing to a separate package whose results we can just import, and remove the dependency on grako.

**Comment by rspeer** [comment]
5.5 no longer depends on generating grammars with Grako.
