### ISSUE TITLE
adding languages.

### ISSUE THREAD

**Issue by 0985057576qr** [commonsense/conceptnet5#69]
Good afternoon. a correct algorithm to add a new language? (if possible, will be grateful for a complete description) that would be in the future, you can add it to their database sushestvuet languages. if I am not mistaken they have right now 27.

**Comment by rspeer** [comment]
I'm not sure if this is what you're asking, but ConceptNet has good support for 78 languages, and support at all for a total of 304. The list is at: https://github.com/commonsense/conceptnet5/wiki/Languages

Given that, adding new languages isn't something we should need to do for a while, unless there's a language we have input data for that we simply overlooked. What's important is putting together data sources to improve the languages that are already in ConceptNet.
