### ISSUE TITLE
use C# and F#?

### ISSUE THREAD

**Issue by 0985057576qr** [commonsense/conceptnet5#70]
Good afternoon. Whether the use is possible (or integration) C # or F #, how should this occur (sovmesno with you or is it merely our personal business)? PS except for a specified language you like a python.
I inform in advance we are a small company, and we have, alas neodin programmer once worked with python in horror as pischat do not even want him prekosotsya (study). our main languages ​​that use C # as well as begin to implement the F #.

Thank you in advance for your help

**Comment by rspeer** [comment]
The ConceptNet API is a REST API that you can access from any programming language.

You should be able to follow the example of https://github.com/commonsense/conceptnet5/wiki/API#quick-start , using your preferred HTTP and JSON libraries for C# instead of `requests` for Python.
