### ISSUE TITLE
API bug.

### ISSUE THREAD

**Issue by zhouhoo** [commonsense/conceptnet5#73]
when I post a request: http://api.conceptnet.io/related/list/en/capital?filter=/c/en
It works well.

How ever , when post a reques about Chinese term : http://api.conceptnet.io/related/list/zh/首都?filter=/c/zh
I got a 500 error.  then I remove filter parameter, It turns out to work well too.

So the API for other language doesn't support well?

**Comment by rspeer** [comment]
I tried it in some other languages, but apparently Chinese has a very silly bug -- an off-by-one error in slicing the matrix due to the fact that Chinese vectors are last in alphabetical order (with language code `zh`). I'll fix it.

**Comment by rspeer** [comment]
Fixed and deployed now. Thanks for the report.
