### ISSUE TITLE
Function behind web api field

### ISSUE THREAD

**Issue by arekbulski** [commonsense/conceptnet5#74]
Which function is called when web api is queried? I would like to call it locally.

**Comment by rspeer** [comment]
All the functions that the web API uses can be found in the `conceptnet_web.responses` module, which calls various things in `conceptnet5.db.query` and `conceptnet5.vectors.query`.

Here's a link to responses.py (sorry that it doesn't have many comments):

https://github.com/commonsense/conceptnet5/blob/master/web/conceptnet_web/responses.py

Feel free to ask questions in [the Gitter chat room](https://gitter.im/commonsense/conceptnet5).
