### ISSUE TITLE
setup.py entry_points console_scripts missing

### ISSUE THREAD

**Issue by zhouhoo** [commonsense/conceptnet5#78]
@rspeer  When I look through the setup.py, I found an entry_points script defined here can not be found in source code. `'cn5-build-index = conceptnet5.hashtable.cli:run_build',` where is it ?  there should be a hashtable sub folder in conceptnet5 folder, isn't it ? Here is the pazzle part of setup.py.
entry_points = {
        'console_scripts': [
            'cn5-vectors = conceptnet5.vectors.cli:cli',
            'cn5-build-index = conceptnet5.hashtable.cli:run_build',
            'cn5-read = conceptnet5.readers.cli:cli',
            'cn5-convert = conceptnet5.formats.convert:cli',
            'cn5-db = conceptnet5.db.cli:cli'
        ]
    }

**Comment by rspeer** [comment]
Ah, that functionality was replaced by `cn5-db`, so I should remove the console script for `cn5-build-index`.
