### ISSUE TITLE
problem with zh_frames.json 

### ISSUE THREAD

**Issue by zhouhoo** [commonsense/conceptnet5#79]
1. I commit changes to zh_frames.json file, but your server still not rebuild or redeploy. I still get wrong answer from  REST API. for example , one wrong result is : `('[[总经理]] 不想要 [[烂员工]]。', '总经理', '烂员工', 'Desires')`

2. there is some replace with {2} and {1}  in zh_frames.json to produce right meaning. 
`"3378": {
    "text": "{2} 有 {1}。", 
    "relation": "/r/AtLocation"
  }, `
However, problem is still there. for example :  `('[[公司]] 有 [[总裁]]。', '公司', '总裁', 'AtLocation')`  .  This means thant  公司  is  start node, 总裁 is end node, relation is AtLocation. which is totall not in the right direction. 

`def handle_raw_assertion(line):
    parts = line.split(', ')
    user, frame_id, concept1, concept2 = parts
    fdata = FRAME_DATA[frame_id]
    ftext = fdata['text']
    rel = fdata['relation']

    surfaceText = ftext.replace('{1}', '[[' + concept1 + ']]').replace('{2}', '[[' + concept2 + ']]')
    start = standardized_concept_uri('zh_TW', concept1)
    end = standardized_concept_uri('zh_TW', concept2)
    source = {
        'contributor': '/s/contributor/petgame/' + user,
        'activity': '/s/activity/ptt/petgame'
    }
    yield make_edge(rel, start, end, dataset='/d/conceptnet/4/zh',
                    license=Licenses.cc_attribution, sources=[source],
                    surfaceText=surfaceText, weight=1)`

**Comment by rspeer** [comment]
I haven't deployed the new build of ConceptNet yet.

The previous PR you made was helpful: could you make another one that fixes the reversed frames you found?

**Comment by zhouhoo** [comment]
The code here look like ok ,but the result is wrong, maybe  the dataset cause the problem .  I now  build my  local environment  to debug this wired bug.  I will notice you as soon as I fix it.  You can also have a try .

**Comment by rspeer** [comment]
The problem, as I understand it, is in the data that was provided by NTU (which turned into `zh_frames.json`). When a sentence pattern needs to put `{2}` before `{1}`, sometimes they just end up swapped, with `{1}` before `{2}`. The problem here is I can't read Chinese, so I have a hard time recognizing when the grammar of a sentence is backwards.

**Comment by ylkuo** [comment]
This might be a problem in the data I generated. Let me take a look and update you two then.

**Comment by rspeer** [comment]
Thanks, Yen-Ling. I think the negation problem was my fault -- I just lost track of that information because the representation of negations changed between ConceptNet 4 and 5 -- but the swapped `{2}` and `{1}` were in the last database I got from your group.

**Comment by zhouhoo** [comment]
Thank you . today I run my local version filter out Chinese only Using data source conceptnet4 and ptt_petgame.(The codes says Chinese conceptions only come from ptt_petgame). But I got smaller relations  of 15, almost Half of what I got from your Server through REST API.   So why this happened?

**Comment by rspeer** [comment]
A couple of questions, probably for @zhouhoo :

You mention `{2} 有 {1}。` being in the wrong order. Does this mean "{2} has {1}"? If so, then it's sort of correct to infer that {1} is in the location of {2}. If my pocket has coins in it, then the coins are in my pocket. But we could also make this more precise by mapping `{1} 有 {2}。`  to the relation /r/HasA, which wasn't available in ConceptNet 4.

Frame 3380 is a UsedFor frame, with text `{2} 的時候可能會用到 {1}。` . Is it correct for `{2}` to come before `{1}` here? Is `{2}` the purpose and `{1}` the thing being used, or do they need to be switched?

**Comment by ylkuo** [comment]
I checked the txt file I sent to Rob before. I think both the data and the frame mapping in zh_frames.json are correct.

For frame 3378, `{2} 有 {1}。` , I saw `{公園 (park)} 有 {樹 (tree)}` in txt file and it should be `AtLocation(樹 (tree), 公園 (park))`. 

Same for frame 3380, `{2} 的時候可能會用到 {1}。`, I saw `{喝水 (drink water)} 的時候可能會用到 {杯子 (cup)}。` in txt file and it should be `UsedFor(杯子 (cup), 喝水 (drink water))`.

Although code looks correct to me, but it seems something is wrong in conversion, all ``UsedFor`` assertions for ``杯子 (cup)`` are reversed:
<img width="550" alt="conceptnet5_zh_cup_edges" src="https://cloud.githubusercontent.com/assets/703314/21250538/04c36d92-c314-11e6-96bd-746086ce4279.png">

**Comment by rspeer** [comment]
Thanks. Okay, so the data is correct but the reversed frames are being *displayed* wrong. That's due to the problem zhouhoo identified in the original bug report, which I have a fix for on the `chinese-fixes-5.5` branch.

**Comment by zhouhoo** [comment]
Ah, actually speaking, the problem is maybe caused by the ' label' issue ,whice I have already open a issue named 'node structure miss used' and still not getting a answer.  I firstly got start node information from 'label', then I got the reversed node for some relations({1} is behind {2} ) in zh_frames.json. Now I  change to 'term', information extracted ok.  
` "start": {
        "@id": "/c/zh/气泡",
        "label": "水族箱",
        "language": "zh",
        "term": "/c/zh/气泡"
      },
"end": {
        "@id": "/c/zh/水族箱",
        "label": "气泡",
        "language": "zh",
        "term": "/c/zh/水族箱"
      },`

You mentioned you fix the bug in branch **chinese-fixes-5.5** , but  you just start them,  the label issue is still there.  Maybe you need to fix code in db/qurey.py.

**Comment by rspeer** [comment]
I'm not sure what you're asking. Has the number of Chinese assertions decreased when you run the complete build?

The fixes to the frames are deployed now. Version 5.5.2 is deployed and running on conceptnet.io.

**Comment by zhouhoo** [comment]
Sorry for my poor English. Both the assertions and relation type decrease tested on same case.  the  whole Chinese  relation type amount I got from conceptnet.io is 22, But got 16 locally built from conceptnet4 ,dbpedia and ppt_petgame.  As the code say and my look over , Chinese concepts only build from those three readers ,  isn't it?

**Comment by rspeer** [comment]
There are Chinese assertions in Open Multilingual WordNet -- does that make the difference?
