### ISSUE TITLE
dbpedia raw data not avaliable

### ISSUE THREAD

**Issue by zhouhoo** [commonsense/conceptnet5#82]
When download dbpedia data with this url: http://conceptnet.s3.amazonaws.com/raw-data/2016/dbpedia/dbpedia_en ,  request show error, no suckkey.

**Comment by rspeer** [comment]
Does this come up at some point in the build process? That's not a URL it should be trying to download from, and I don't see such a URL in the Snakefile. It's trying to download from URLs such as https://conceptnet.s3.amazonaws.com/raw-data/2016/dbpedia/instance_types_en.tql.bz2 .

**Comment by rspeer** [comment]
Whatever this was, I am fairly sure it's resolved -- I can run the build process from scratch, including downloading raw data, on a new computer.
